//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication2.Models.Entity
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class FGDBEntities1 : DbContext
    {
        public FGDBEntities1()
            : base("name=FGDBEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<DiscountTBL> DiscountTBL { get; set; }
        public virtual DbSet<ProductTBL> ProductTBL { get; set; }
        public virtual DbSet<UserTBL> UserTBL { get; set; }
    }
}
